services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - ./apps/api-gateway/.env.docker
    ports:
      - 3000:3000
    depends_on:
      - users-service
      - posts-service

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    env_file:
      - ./apps/auth-service/.env.docker
    ports:
      - 3001:3001
    depends_on:
      rabbitmq:
        condition: service_healthy

  users-service:
    build:
      context: .
      dockerfile: ./apps/users-service/Dockerfile
    env_file:
      - ./apps/users-service/.env.docker
    ports:
      - 3002:3002
    depends_on:
      users-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  users-db:
    image: postgres:15-alpine
    restart: always
    user: postgres
    env_file:
      - ./apps/users-service/.env.docker
    volumes:
      - users-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  posts-service:
    build:
      context: .
      dockerfile: ./apps/posts-service/Dockerfile
    env_file:
      - ./apps/posts-service/.env.docker
    ports:
      - 3003:3003
    depends_on:
      posts-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  posts-db:
    image: postgres:15-alpine
    restart: always
    user: postgres
    env_file:
      - ./apps/posts-service/.env.docker
    volumes:
      - posts-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  users-db-data:
  posts-db-data:
